### PR TITLE
Extended example.

### PR DESCRIPTION
**Pull request by georgerappel**
Added some stuff to the example for people that, just like me, needs to run anything after a set period of time,

### CODE REVIEW

**Comment by Kman1595** [comment]
antoniom, I was wondering how to implement this project into my code? Did you make a library, or is the like a copy paste type thing?

**Comment by georgerappel** [comment]
@Kman1595 I copied the "Chronometer.java" file into my project's package and it worked perfectly.

**Comment by Kman1595** [comment]
@georgerappel And you still used the normal android chronometer object? or did you import the "Chronometer.java" file, and use methods from there?

**Comment by georgerappel** [comment]
@Kman1595 Yes, use the normal chronometer.

**Pull request merged**
